[package]
name = "checkers-rust"
version = "0.1.0"
authors = ["cljacoby <cljacoby@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
mut_static = "5.0.0"
lazy_static = "1.0.2"